# Generated by Django 4.2.25 on 2025-10-27 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('host_session', models.CharField(max_length=100)),
                ('current_stage', models.CharField(choices=[('lobby', 'Лобби'), ('roles', 'Показ ролей'), ('coordinates', 'Показ координат'), ('voting', 'Голосование'), ('results', 'Результаты раунда'), ('game_over', 'Игра окончена')], default='lobby', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('human_coords_to_win', models.IntegerField(default=0)),
                ('visited_human_coords_count', models.IntegerField(default=0)),
                ('game_over_status', models.CharField(choices=[('playing', 'В игре'), ('aliens_win', 'Пришельцы победили'), ('humans_win', 'Люди победили')], default='playing', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('avatar_id', models.CharField(default='1', max_length=20)),
                ('role', models.CharField(blank=True, choices=[('human', 'Человек'), ('alien', 'Пришелец')], max_length=10, null=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game_app.gamesession')),
            ],
            options={
                'unique_together': {('session_id', 'game')},
            },
        ),
        migrations.CreateModel(
            name='GameCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_name', models.CharField(max_length=100)),
                ('resource_description', models.CharField(max_length=200)),
                ('is_alien_coord', models.BooleanField(default=False)),
                ('was_visited', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='game_app.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_card', to='game_app.player')),
            ],
        ),
    ]
