# Generated by Django 5.2.7 on 2025-10-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_over_status',
            field=models.CharField(choices=[('playing', 'В игре'), ('aliens_win', 'Пришельцы победили'), ('humans_win', 'Люди победили')], default='playing', max_length=20),
        ),
    ]
