# Generated by Django 4.2.25 on 2026-01-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='is_chaos_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='special_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, choices=[('human', 'Человек'), ('alien', 'Пришелец'), ('scientist', 'Ученый')], max_length=10, null=True),
        ),
    ]
