# Generated by Django 4.2.25 on 2026-04-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_gamesession_is_chaos_mode_player_special_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='is_chaos_mode',
        ),
    ]
