# Generated by Django 4.2.25 on 2026-04-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_remove_gamesession_is_chaos_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecoordinate',
            name='resource_description',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_alive',
        ),
    ]
