# Generated by Django 5.2.7 on 2025-10-22 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_code", models.CharField(blank=True, max_length=10, unique=True)),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("lobby", "Лобби"),
                            ("roles", "Показ ролей"),
                            ("coordinates", "Показ координат"),
                            ("voting", "Голосование"),
                            ("results", "Результаты раунда"),
                            ("game_over", "Игра окончена"),
                        ],
                        default="lobby",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("human_coords_to_win", models.IntegerField(default=0)),
                ("visited_human_coords_count", models.IntegerField(default=0)),
                (
                    "game_over_status",
                    models.CharField(
                        choices=[
                            ("playing", "В игре"),
                            ("aliens_win", "Пришельцы победили"),
                            ("humans_win", "Люди победили"),
                        ],
                        default="playing",
                        max_length=20,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerInGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=50)),
                ("avatar_id", models.CharField(default="1", max_length=20)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[("human", "Человек"), ("alien", "Пришелец")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_alive", models.BooleanField(default=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.gamesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "game")},
            },
        ),
        migrations.CreateModel(
            name="GameCoordinate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coordinate_name", models.CharField(max_length=100)),
                ("resource_description", models.CharField(max_length=200)),
                ("is_alien_coord", models.BooleanField(default=False)),
                ("was_visited", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinates",
                        to="game.gamesession",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinate_card",
                        to="game.playeringame",
                    ),
                ),
            ],
        ),
    ]
