# Generated by Django 5.2.7 on 2025-10-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamecoordinate",
            name="votes",
            field=models.IntegerField(
                default=0,
                help_text="Количество голосов за эту координату в этом раунде",
            ),
        ),
        migrations.AddField(
            model_name="playeringame",
            name="has_voted",
            field=models.BooleanField(
                default=False, help_text="Проголосовал ли игрок в этом раунде"
            ),
        ),
    ]
