# Generated by Django 5.2.7 on 2025-10-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamecoordinate_votes_playeringame_has_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gamecoordinate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playeringame',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
